# SF Bay Area (Alameda, CA)
location:
  latitude: 37.7653
  longitude: -122.2416
max_light_distance: 0.3048  # meters, about one foot
areas:
  living_room_window:
    bearing: 90
    window_height: 1.2
    device: living_room_blind
  kitchen_window:
    bearing: 135
    window_height: 1.2
    device: kitchen_blind
